@echo off
echo Starting Portfolio App...
cd portfolio-app
echo Installing dependencies if missing...
if not exist node_modules call npm install
echo Starting Development Server...
call npm run dev -- --open
pause
